# .github/release.yml

changelog:
  exclude:
    labels:
      - updatebot
  categories:
  - title: ✨ New Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 📚 Documentation
    labels:
      - documentation
  - title: ⬆️ Dependencies
    labels:
      - dependencies
  - title: 💥 Breaking Changes
    labels:
      - breaking-change
  - title: 🚀 Performance Improvements
    labels:
      - performance
  - title: 🎨 UI/UX Changes
    labels:
      - ui-ux
  - title: 🚧 Work in Progress
    labels:
      - work-in-progress
  - title: 🌐 Internationalization
    labels:
      - i18n
  - title: 🩹 Fixes
    labels:
      - fix
  - title: 🔥 Hotfixes
    labels:
      - hotfix
  - title: 🔨 Other Changes
    labels:
      - "*"
      