name: Backport to Develop

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Determine Release Version
        id: version
        run: |
          # Configurar el token de acceso personal directamente en los comandos de Git

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git submodule foreach 'git config --local credential.helper "store --file=.git/credentials"'

          git checkout master && git fetch && git pull -f

          LAST_RELEASE=$(git describe --abbrev=0 --tags master)
          VERSION=$(echo $LAST_RELEASE | grep -oP 'release/\d+\.\d+\.\d+')

          echo "::set-output name=version::$VERSION"

      - name: Backport to Develop
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git submodule foreach 'git config --local credential.helper "store --file=.git/credentials"'

          echo "Starting backport"
          git checkout develop
          git pull origin develop
          git pull --recurse-submodules
          git submodule update --remote --recursive

          git checkout master
          git pull origin master

          git pull --recurse-submodules
          git submodule update --remote --recursive

          git checkout develop
          git merge -X ours master --allow-unrelated-histories
          git push origin develop

      - name: Create Pull Request
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git submodule foreach 'git config --local credential.helper "store --file=.git/credentials"'

          # Obtén el SHA del último commit en la rama develop
          DEVELOP_SHA=$(git rev-parse develop)

          # Crea un Pull Request directamente desde master a develop

          curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "{\"base\":\"develop\",\"head\":\"master\",\"title\":\"Backport to Develop\",\"body\":\"Automated backport from master\",\"base\":\"develop\",\"head\":\"master\"}"

        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

