name: Release PR
 
on:
  push:
    branches:
      - 'release/*'

jobs:
  release-PR:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      
    steps:
      - name: Check if PRs exist
        run: |
          if curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master&head=${{ github.event.ref }}" | jq -e '.[]' > /dev/null; then
            echo "PRs exist. Exiting workflow."
            exit 0
          else
            echo "No PRs found, continue with the workflow."
          fi
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure gitCLI
        id: version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git submodule foreach 'git config --local credential.helper "store --file=.git/credentials"'  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create PR
        run: |
          # Crea un Pull Request directamente desde la release a master
          VERSION_NUMBER=$(echo ${{ github.event.pull_request.head.ref }}  | grep -oP '(\d+\.\d+\.\d+)')
          PR_URL=$(curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "{\"base\":\"master\",\"head\":\"${{ github.event.ref }}\",\"title\":\"Release ${VERSION_NUMBER}\",\"body\":\"Automated PR for release ${VERSION_NUMBER}\"}" \
            | jq -r '.html_url')
          # Extra: Esperar a que GitHub termine de procesar el PR
          sleep 10
          
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
