name: Release PR
 
on:
  push:
    branches:
      - 'release/*'

jobs:
  release-PR:
    runs-on: ubuntu-latest
    if: >
      curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master&head=${{ github.event.ref }}" | jq -e '.[]' > /dev/null
      
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Determine Release Version
        id: version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git submodule foreach 'git config --local credential.helper "store --file=.git/credentials"'

      - name: Create PR
        run: |
          # Crea un Pull Request directamente desde la release a master
          PR_URL=$(curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "{\"base\":\"master\",\"head\":\"${{ github.event.ref }}\",\"title\":\"Release ${{ github.event.ref }}\",\"body\":\"Automated PR for release ${{ github.event.ref }}\"}" \
            | jq -r '.html_url')
          # Extra: Esperar a que GitHub termine de procesar el PR
          sleep 10
          
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
