name: Release Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Release Version
      if: >
        github.event.pull_request.merged == true &&
        github.event.pull_request.base.ref == 'master' &&

        startsWith(github.event.pull_request.head.ref, 'release/')

      run: |
        # Obtener la versión de la rama de release
        VERSION=$(echo ${{ github.event.pull_request.head.ref }} | grep -oP 'release/\d+\.\d+\.\d+')

        # Crear un tag y generar una versión
        git tag $VERSION
        git push origin $VERSION
