name: Release Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Extract branch name
      run: echo "BRANCH_NAME=${{ github.actor }}" >> $GITHUB_ENV

    - name: Release Version
      if: |
        github.event_name == 'push' &&
        github.event.ref == 'refs/heads/master' &&
        startsWith(env.BRANCH_NAME, 'refs/heads/release/')

      run: |
        # Obtener la versión de la rama de release
        VERSION=$(echo $BRANCH_NAME | grep -oP 'refs/heads/release/\d+\.\d+\.\d+')

        # Crear un tag y generar una versión
        git tag $VERSION
        git push origin $VERSION
